import { describe, expect, it } from "vitest";
import { createCompileProjectHandler, createCompileNetworksHandler } from "./compile-tasks.js";
import type { PhaseExecutor, SpawnResult } from "../../engine/wizard/phase-executor.js";
import type { WizardProgress } from "../../engine/wizard/types.js";

const okResult: SpawnResult = { exitCode: 0, stdout: "", stderr: "" };
const failResult: SpawnResult = { exitCode: 1, stdout: "", stderr: "error" };

const fullContext = {
	binaryFolder: "/path/to/Binaries",
	hisePath: "/hise",
	jucerFile: "/path/to/Binaries/AutogeneratedProject.jucer",
	projectName: "Demo Project",
	configuration: "Release",
};

function withPlatform<T>(platform: NodeJS.Platform, fn: () => Promise<T>): Promise<T> {
	const original = process.platform;
	Object.defineProperty(process, "platform", { value: platform, configurable: true });
	return fn().finally(() => {
		Object.defineProperty(process, "platform", { value: original, configurable: true });
	});
}

describe("createCompileProjectHandler", () => {
	it("spawns build script from context", async () => {
		await withPlatform("linux", async () => {
			const spawnCalls: Array<{ cmd: string; args: string[] }> = [];
			const executor: PhaseExecutor = {
				spawn: async (cmd, args, _opts) => {
					spawnCalls.push({ cmd, args });
					if (cmd === "cat") return { exitCode: 0, stdout: "make CONFIG=Release", stderr: "" };
					return okResult;
				},
			};

			const handler = createCompileProjectHandler(executor);
			const progress: WizardProgress[] = [];
			const result = await handler({}, (p) => progress.push(p), undefined, fullContext);

			expect(result.success).toBe(true);
			expect(spawnCalls[0]!.cmd).toBe("cat");
			expect(spawnCalls[0]!.args).toEqual(["/path/to/Binaries/batchCompileLinux"]);
			expect(spawnCalls[1]!.cmd).toBe("bash");
		});
	});

	it("fails when context is missing", async () => {
		const handler = createCompileProjectHandler({ spawn: async () => okResult });
		const result = await handler({}, () => {}, undefined, undefined);
		expect(result.success).toBe(false);
		expect(result.message).toContain("Missing build paths");
	});

	it("fails when context has no binaryFolder", async () => {
		const handler = createCompileProjectHandler({ spawn: async () => okResult });
		const result = await handler({}, () => {}, undefined, { hisePath: "/hise" });
		expect(result.success).toBe(false);
		expect(result.message).toContain("Missing build paths");
	});

	it("runs make in MacOSXMakefile on darwin", async () => {
		await withPlatform("darwin", async () => {
			const spawnCalls: Array<{ cmd: string; args: string[]; cwd?: string; env?: Record<string, string> }> = [];
			const executor: PhaseExecutor = {
				spawn: async (cmd, args, opts) => {
					spawnCalls.push({ cmd, args, cwd: opts.cwd, env: opts.env });
					return okResult;
				},
			};
			const handler = createCompileProjectHandler(executor);
			const result = await handler({}, () => {}, undefined, fullContext);
			expect(result.success).toBe(true);
			const makeCall = spawnCalls.find((c) => c.cmd === "make");
			expect(makeCall).toBeDefined();
			expect(makeCall!.args).toEqual(["CONFIG=Release", "-j1"]);
			expect(makeCall!.cwd).toBe("/path/to/Binaries/Builds/MacOSXMakefile");
			expect(makeCall!.env?.JUCE_JOBS_CAPPED).toBe("1");
		});
	});

	it("threads macArchitecture into the make invocation when provided", async () => {
		await withPlatform("darwin", async () => {
			const spawnCalls: Array<{ cmd: string; args: string[] }> = [];
			const executor: PhaseExecutor = {
				spawn: async (cmd, args) => {
					spawnCalls.push({ cmd, args });
					return okResult;
				},
			};
			const handler = createCompileProjectHandler(executor);
			await handler({}, () => {}, undefined, { ...fullContext, macArchitecture: "arm64" });
			const makeCall = spawnCalls.find((c) => c.cmd === "make");
			expect(makeCall!.args).toContain("TARGET_ARCH=-arch arm64");
		});
	});

	it("reports compilation failure", async () => {
		await withPlatform("linux", async () => {
			const executor: PhaseExecutor = {
				spawn: async (cmd) => {
					if (cmd === "cat") return { exitCode: 0, stdout: "make", stderr: "" };
					return failResult;
				},
			};

			const handler = createCompileProjectHandler(executor);
			const result = await handler({}, () => {}, undefined, fullContext);

			expect(result.success).toBe(false);
			expect(result.message).toContain("Compilation failed");
		});
	});
});

describe("createCompileNetworksHandler", () => {
	it("uses the same JUCE compile path as plugin export", async () => {
		await withPlatform("linux", async () => {
			const spawnCalls: Array<{ cmd: string; args: string[] }> = [];
			const executor: PhaseExecutor = {
				spawn: async (cmd, args) => {
					spawnCalls.push({ cmd, args });
					if (cmd === "cat") return { exitCode: 0, stdout: "make CONFIG=Release", stderr: "" };
					return okResult;
				},
			};

			const handler = createCompileNetworksHandler(executor);
			const result = await handler({}, () => {}, undefined, fullContext);

			expect(result.success).toBe(true);
			expect(spawnCalls[0]!.cmd).toBe("cat");
			expect(spawnCalls[0]!.args).toEqual(["/path/to/Binaries/batchCompileLinux"]);
			expect(spawnCalls[1]!.cmd).toBe("bash");
		});
	});

	it("fails when context is missing", async () => {
		const handler = createCompileNetworksHandler({ spawn: async () => okResult });
		const result = await handler({}, () => {}, undefined, {});
		expect(result.success).toBe(false);
		expect(result.message).toContain("Missing build paths");
	});
});
